name: 'Main: Publish to Maven repo'

on:
  push:
    branches: [ master ]

jobs:
  publish_to_maven_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            publish
              -PmultiverseUsername=${{ secrets.REPOSILITE_REPO_USERNAME }}
              -PmultiversePassword=${{ secrets.REPOSILITE_REPO_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
